version: 2

jobs: 

  build:
    machine:
      image: ubuntu-2404:2024.08.1
    steps:
      # install actual docker version
      - run: sudo apt-get update
      - run: sudo apt-get install ca-certificates curl
      - run: sudo install -m 0755 -d /etc/apt/keyrings
      - run: sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
      - run: sudo chmod a+r /etc/apt/keyrings/docker.asc
      - run: |
              echo \
                "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
                $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
                sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      - run: sudo apt-get update
      - run: sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      # enable experimental docker features for buildx
      - run: docker info

      # register qemu and create multi-architecture build instance
      - run: docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
      - run: docker buildx create --name mybuilder
      - run: docker buildx use mybuilder
      - run: docker buildx inspect --bootstrap
      
      # build and push bintcoind
      - run: git clone -b "$CIRCLE_BRANCH" https://github.com/legacycode/rtlsdr-docker.git .
      - run: echo 'export DOCKER_TAG=${DOCKER_USERNAME}/rtlsdr:${CIRCLE_BRANCH}${CIRCLE_TAG}' >> $BASH_ENV
      - run: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
      - run: |
          docker buildx build \
          --platform linux/amd64,linux/arm64,linux/386,linux/arm/v7 \
          --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
          --build-arg VCS_REF=$CIRCLE_SHA1 . -t ${DOCKER_TAG} --push

workflows: 
  version: 2
  untagged: 
    jobs: 
      - build
